### ISSUE TITLE
How to add directory contents

### ISSUE THREAD

**Issue by vinsworldcom** [mathiassv/MZCrumbBar#1]
Very interesting implementation of bread crumb navigation.  I've been looking for an open source alternative in C++ and found yours.

In the example, you've hardcoded "C:\Windows\System32" but I'd like to be able to use for real file system navigation.  I suppose I could use something like [this](https://docs.microsoft.com/en-us/windows/win32/fileio/listing-the-files-in-a-directory) (FindFirstFile(), FindNextFile(), and FindClose()) to list files in the directory that MZCrumbBar OnLButtonClick(), but is there a control to pass them to such that a drop down can be populated?  I'm thinking like the way Windows Explorer address bar works:

![image](https://user-images.githubusercontent.com/9657169/81883524-6f4f7280-9563-11ea-8ce0-47d9d704713c.png)

I'm thinking like this:

![image](https://user-images.githubusercontent.com/9657169/81883642-c2292a00-9563-11ea-97cf-eee1cb16f411.png)

Cheers.

**Comment by mathiassv** [comment]
MZCrumbBar is a base controller for creating the UI,
I would create a new controller that inherit from MZCrumbBar,  eg  FileSystemCrumbBarCtrl.
And then have filesystem unique functions in that.

And then when you click on a crumbbaritem.
(eg override  OnLButtonClick( CrumbBarItem* pItem , const CPoint& pt) )
You create and show a popup that path there

And to get the entire path up to an crumbbar item use  
`CString GetPath(CrumbBarItem* pItem);`
